name: lair_pages
description: Datetime and schema validation tests for Lair static JSON schedules.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lair:
    path: ../Lair

dev_dependencies:
  test: ^1.24.0
